name: Generate Package Lock

on:
  workflow_dispatch:

jobs:
  generate-package-lock:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Generate package-lock.json
      run: |
        npm install
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add package-lock.json
        git commit -m "Add package-lock.json"
        git push
